// 纯路由表：状态 × 事件 → 下一状态
// 未列出的事件 = 非法流转，dispatch 会返回 consumed:false 直接忽略
import { STATUS, EVENTS } from './types'

export const transitions = {
  [STATUS.IDLE]: {
    [EVENTS.USER_INPUT]: STATUS.UNDERSTANDING
  },
  [STATUS.UNDERSTANDING]: {
    [EVENTS.LLM_READY]: STATUS.AWAITING_CONFIRM
  },
  [STATUS.AWAITING_CONFIRM]: {
    [EVENTS.USER_CONFIRM]: STATUS.COMMITTING,
    [EVENTS.USER_SUPPLEMENT]: STATUS.UNDERSTANDING,
    [EVENTS.USER_CANCEL]: STATUS.IDLE
  },
  [STATUS.COMMITTING]: {
    [EVENTS.REQ_SENT]: STATUS.VALIDATING
  },
  [STATUS.VALIDATING]: {
    [EVENTS.BIZ_PASS]: STATUS.COMPLETE,
    [EVENTS.BIZ_FAIL]: STATUS.REVISING,
    [EVENTS.USER_CANCEL]: STATUS.IDLE
  },
  [STATUS.REVISING]: {
    [EVENTS.USER_INPUT]: STATUS.COMMITTING,
    [EVENTS.USER_CANCEL]: STATUS.IDLE
  },
  [STATUS.COMPLETE]: {
    [EVENTS.USER_SUBMIT]: STATUS.SUBMITTING,
    [EVENTS.USER_AMEND]: STATUS.COMMITTING
  },
  [STATUS.SUBMITTING]: {
    [EVENTS.BIZ_OK]: STATUS.DONE,
    [EVENTS.BIZ_ERR]: STATUS.REVISING
  },
  [STATUS.DONE]: {
    [EVENTS.RESET]: STATUS.IDLE
  }
}
